# Generated by Django 5.1.2 on 2025-06-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=80, null=True)),
                ("class_numeric", models.IntegerField(null=True)),
                ("section", models.CharField(max_length=5, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("updation_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("details", models.TextField(null=True)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                (
                    "subject_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("updation_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("roll_id", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("dob", models.CharField(max_length=100, null=True)),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
                ("updation_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resultapp.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField(null=True)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                ("updation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resultapp.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resultapp.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resultapp.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=1)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("updation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resultapp.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resultapp.subject",
                    ),
                ),
            ],
        ),
    ]
